version: '3'
services:
  annonce:
    restart: always
    build: .
    ports:
      - 80:4000
  mongo-db:
    image: mongo
    ports:
      - 27017:27018
    volumes:
      - mongodb://data/db
volumes:
  mongodb:


